name: Deploy to GCP

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: rawson-devops-project
  REGION: us-central1
  REPO: devops-repo
  SERVICE: devops-app
  BUCKET_NAME: devops-challenge-bucket
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev
        

      - name: Build Image
        run: |
         docker build -f Dockerfile -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/app:latest .

      - name: Push Image
        run: |
          docker push  $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/app:latest 
        
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy app \
          --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/app:latest \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars BUCKET_NAME=$BUCKET_NAME

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve